<html>
<p>
    You may have noticed that in Self Validation task we throw exception -> this behaviour breaks the flow. Please look at
    the main function, after you do implement the rest of the task. If you choose to run uncommented version, it will print
    even though there is an invalid value. However, if you decide to run the commented version, the print will never happen.
    <br/>
    This is not the best thing to do so we would change the way we create TimeSignatures to be sure that exceptions are not thrown.
</p>

<p>
    First of all, we are going to use a concept that origins in functional programming, but will help us in here.
    So, if you don't know about <i>sealed classes</i> in Kotlin, read the
    <a href="https://kotlinlang.org/docs/reference/sealed-classes.html">documentation</a>.
</p>

<p>
    As you can see in the code in the example we changed our TimeSignature class to ValidTimeSignatures and
    extend the newly created sealed class TimeSignature.
</p>
<p>
    We have also created an object InvalidTimeSignature that also extends TimeSignature.
    If you are unfamiliar with objects in Kotlin, please read the documentation: <a href="https://kotlinlang.org/docs/tutorials/kotlin-for-py/objects-and-companion-objects.html#object-declarations">link</a>.
</p>
<p>
    Now you are going to implement the <b>create</b> and fix <b>of</b> method
    that create ValidTimeSignatures or returns the InvalidTimeSignature object.
</p>
</html>